# Generated by Django 4.2.3 on 2024-02-21 05:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casting_schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_date', models.DateField()),
                ('complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Casting Schedule',
            },
        ),
        migrations.CreateModel(
            name='Drawings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='drawings/')),
            ],
            options={
                'verbose_name_plural': 'Drawings',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12)),
                ('expected_wastage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('supplier_increments', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('datestamp', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('panel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('panel_width', models.DecimalField(decimal_places=2, max_digits=12)),
                ('panel_length', models.DecimalField(decimal_places=2, max_digits=12)),
                ('panel_volume', models.DecimalField(decimal_places=2, max_digits=12)),
                ('panel_position_x', models.DecimalField(decimal_places=2, max_digits=12)),
                ('panel_position_y', models.DecimalField(decimal_places=2, max_digits=12)),
                ('panel_rotation', models.BooleanField(default=False)),
                ('schedule_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.casting_schedule')),
            ],
            options={
                'verbose_name_plural': 'Panels',
            },
        ),
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('stocktake_id', models.AutoField(primary_key=True, serialize=False)),
                ('stocktake_type', models.CharField(max_length=100)),
                ('datestamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stocktake',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('webpage', models.URLField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Stocktake_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.materials')),
                ('stocktake_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.stocktake')),
            ],
            options={
                'verbose_name_plural': 'Stocktake Data',
            },
        ),
        migrations.CreateModel(
            name='Panels_bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=12)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.materials')),
                ('panel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.panels')),
            ],
            options={
                'verbose_name_plural': 'Panels BOM',
            },
        ),
        migrations.CreateModel(
            name='Orders_used',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.orders')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.casting_schedule')),
            ],
            options={
                'verbose_name_plural': 'Orders Used',
            },
        ),
        migrations.CreateModel(
            name='Orders_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.materials')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.orders')),
            ],
            options={
                'verbose_name_plural': 'Order Data',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.suppliers'),
        ),
        migrations.AddField(
            model_name='materials',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.suppliers'),
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bom_type', models.IntegerField(default=0)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.materials')),
            ],
            options={
                'verbose_name': 'BOM',
            },
        ),
    ]
