# Generated by Django 4.2.3 on 2024-01-27 12:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('webpage', models.URLField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.suppliers')),
            ],
            options={
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.materials')),
            ],
            options={
                'verbose_name_plural': 'Bom',
            },
        ),
    ]
