# Generated by Django 4.2.3 on 2024-01-23 11:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_suppliers_contact_alter_suppliers_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'verbose_name_plural': 'Suppliers'},
        ),
    ]
