# Generated by Django 4.2.3 on 2024-01-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_delete_bom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={},
        ),
    ]
