# Generated by Django 4.2.3 on 2024-01-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20240128_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
