# Generated by Django 4.2.3 on 2024-01-28 02:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_bom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='expected_wastage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='supplier_increments',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12),
        ),
    ]
