# Generated by Django 4.2.3 on 2024-01-28 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_materials_expected_wastage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('stocktake_id', models.AutoField(primary_key=True, serialize=False)),
                ('datestamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stocktake',
            },
        ),
        migrations.AlterModelOptions(
            name='bom',
            options={'verbose_name': 'BOM'},
        ),
        migrations.CreateModel(
            name='Stocktake_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.materials')),
                ('stocktake_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.stocktake')),
            ],
            options={
                'verbose_name': 'Stocktake Data',
            },
        ),
    ]
