# Generated by Django 4.2.3 on 2024-01-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_stocktake_alter_bom_options_stocktake_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktake',
            options={'verbose_name_plural': 'Stocktake'},
        ),
        migrations.AlterModelOptions(
            name='stocktake_data',
            options={'verbose_name_plural': 'Stocktake Data'},
        ),
    ]
