# Generated by Django 4.2.3 on 2024-02-07 09:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_drawings_options_alter_materials_supplier_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('datestamp', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=100)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='Order_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.materials')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.orders')),
            ],
            options={
                'verbose_name_plural': 'Order Data',
            },
        ),
    ]
