# Generated by Django 4.2.3 on 2024-02-08 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_rename_order_data_orders_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='stocktake_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.suppliers'),
        ),
    ]
