# Generated by Django 4.2.3 on 2024-02-09 02:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_stocktake_stocktake_type_alter_orders_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_data',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
