# Generated by Django 4.2.3 on 2024-02-13 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_orders_data_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('panel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('panel_width', models.DecimalField(decimal_places=2, max_digits=12)),
                ('panel_length', models.DecimalField(decimal_places=2, max_digits=12)),
                ('panel_rotation', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Panels',
            },
        ),
        migrations.CreateModel(
            name='Casting_schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_date', models.DateField(auto_now_add=True)),
                ('panel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.panels')),
            ],
            options={
                'verbose_name_plural': 'Casting Schedule',
            },
        ),
    ]
