# Generated by Django 4.2.3 on 2024-02-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_alter_casting_schedule_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='panels',
            name='panel_position_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panels',
            name='panel_position_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='panels',
            name='panel_rotation',
            field=models.BooleanField(default=False),
        ),
    ]
