# Generated by Django 4.2.3 on 2024-02-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_panels_panel_position_x_panels_panel_position_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panels',
            name='panel_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
