# Generated by Django 4.2.3 on 2024-02-14 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_panels_panel_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casting_schedule',
            name='panel_id',
        ),
        migrations.AddField(
            model_name='casting_schedule',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panels',
            name='schedule_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.casting_schedule'),
        ),
    ]
