# Generated by Django 4.2.3 on 2024-02-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_remove_casting_schedule_panel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='bom_type',
            field=models.IntegerField(default=0),
        ),
    ]
