# Generated by Django 4.2.3 on 2024-02-17 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_panels_bom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_used',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.orders_data')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.casting_schedule')),
            ],
            options={
                'verbose_name_plural': 'Orders Used',
            },
        ),
    ]
