# Generated by Django 4.2.3 on 2024-02-17 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_orders_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_used',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.orders'),
        ),
    ]
